[package]
name = "elfdump"
version = "0.1.0"
edition = "2021"
authors = ["mintsuku moxxydev@gmail.com"]
description = "An elf analyzer written in rust"
license = "MIT"


[dependencies]
clap = { version = "4.5.23", features = ["derive"] }
tabled = "0.17.0"
